### ISSUE TITLE
Review AtomDB API to optimize the use of all MongoDB indexes

### ISSUE THREAD

**Issue by andre-senna** [singnet/das#46]
Currently we have only one method badly named `get_matched_node_name`. We should design a better set of methods with proper functionalities and method names.

Eventually, we may need to create extra indexes in MongoDB in order to make the proposed queries faster in redis_mongo.

**Comment by eddiebrissow** [comment]
# (WIP) MONGODB INDEX RESEARCH

Indexes are special data structures that store a small portion of the collection's data set in an easy to traverse form. The index stores the value of a specific field or set of fields, ordered by the value of the field. 

## Default _id index

MongoDB creates a unique index on the _id field during the creation of a collection. The _id index prevents clients from inserting two documents with the same value for the _id field. You cannot drop this index on the _id field.

## Single Field

User-defined ascending/descending indexes on a single field of a document.

## Compound Index
User-defined indexes on multiple fields, the order of the indexed fields has a strong impact on the effectiveness of a particular index for a given query.

More info:
[Compound Indexes](https://www.mongodb.com/docs/v5.3/core/index-compound/)

### Limitations
- Order can have a strong impact on the query


## Multikey Index

MongoDB uses multikey indexes to index the content stored in arrays. If you index a field that holds an array value, MongoDB creates separate index entries for every element of the array

More info:
[Multikey Indexes](https://www.mongodb.com/docs/v5.3/core/index-multikey/)

### Limitations
- Can increase the index size
- Index can not contain multiple arrays

## Geospacial Index

More info:

[Create a 2d Index](https://www.mongodb.com/docs/v5.3/tutorial/build-a-2d-index/)

## Text indexes

MongoDB provides a text index type that supports searching for string content in a collection. These text indexes do not store language-specific stop words (e.g. "the", "a", "or") and stem the words in a collection to only store root words.

More info:
[Text Indexes](https://www.mongodb.com/docs/v5.3/core/index-text/)


### Limitations
- Need more parameters in query, like the query score to retrieve meaningful data
- Can increase the index size, due to big texts
- More time to create indexes
- Impacts write performance


## Clustered Indexes

Starting in MongoDB 5.3, you can create a collection with a clustered index. Collections created with a clustered index are called clustered collections.

More info:
[Clustered Collections](https://www.mongodb.com/docs/v5.3/core/clustered-collections/#std-label-clustered-collections),
[clusteredIndex](https://www.mongodb.com/docs/v5.3/reference/method/db.createCollection/#std-label-db.createCollection.clusteredIndex)
### Limitations

By default, if a secondary index exists on a clustered collection and the secondary index is usable by your query, the secondary index is selected instead of the clustered index.


## WildCard Indexes

MongoDB supports creating indexes on a field or set of fields to support queries. Since MongoDB supports dynamic schemas, applications can query against fields whose names cannot be known in advance or are arbitrary.

To index the value of all fields in a document (excluding _id), specify "$**" as the index key:

```
db.collection.createIndex( { "$**" : 1 } )
```
More info:

[Wildcard Indexes](https://www.mongodb.com/docs/v5.3/core/index-wildcard/)

[Wildcard Index Restrictions](https://www.mongodb.com/docs/v5.3/reference/index-wildcard-restrictions/#std-label-wildcard-index-restrictions)

### Limitations

- Requires Version 4.2
- Increases the size of the indexes for large databases
-  Can not shard widcard indexes


## Partial Indexes

Partial indexes only index the documents in a collection that meet a specified filter expression. By indexing a subset of the documents in a collection, partial indexes have lower storage requirements and reduced performance costs for index creation and maintenance.

More info:
[Partial Indexes](https://www.mongodb.com/docs/v5.3/core/index-partial/)


## References
[MongoDB's indexes documentation](https://www.mongodb.com/docs/v5.3/indexes/) 
[How MongoDB Clustered Collection Can Boost Query Performance](https://levelup.gitconnected.com/how-mongodb-clustered-collection-can-boost-query-performance-f701fdd751ca)
