### ISSUE TITLE
Review release process

### ISSUE THREAD

**Issue by andre-senna** [singnet/das#56]
Suggested changes:
    
* [x] Update all of the related Dockerfile to use a fixed version of ubuntu, instead of ubuntu-latest

**Comment by levisingularity** [comment]
suggestions:
- [x] The current version unknow error when creating new version (improve exception when the cli cannot get the version)
- [x] in the release script, do not run the unit and integration tests before publishing the new functions in the vultr openfaas
- [x] Create command to run only unit and integration tests by triggering the pipelines
- [x] Create script in das-cli to report all versions of all repos on github, dockerhub, dev and prod server
- [x] another thing that we can put in the script, search for the most updated versions of the packages that belong to each other, for example if we want to update only the functions because it generated a manual version of the query engine, the script will search for the version current version of the query engine and suggest updating the serverless function
- [x] generate a backup file when the script is running
